### ISSUE TITLE
disabledに文字列を指定する

### ISSUE THREAD

**Issue by NigoroJr** [Shougo/neobundle.vim#385]
現在は特定の条件でプラグインを無効にしたいときは、

```vim
call neobundle#config('neocomplete.vim', {
\ 'disabled': !has('lua'),
\ }
```

というように、関数の戻り値を使いますが、TOMLを使う場合には別途`.vimrc`内でconfigを呼び出す必要があります。文字列が指定された場合にはその文字列が`eval`された結果にできるとTOML内にも記述できて便利なのではないでしょうか。つまり、

```toml
[[plugins]]
repository = 'Shougo/neocomplete.vim'
disabled = '!has("lua")'
```

ということです。
