### ISSUE TITLE
Why TOML instead of YAML?

### ISSUE THREAD

**Issue by amerlyq** [Shougo/neobundle.vim#450]
And so it is -- exactly same question as in the header. 
Why not Yaml? It's much more neat and clean considering nested lists.
You can drop ```[[plugins]]``` marker, using exact repo name as root key,  skip quotes on strings, make nesting more stand out, reuse identical config sections by back-references...

Now I, of course, can use something like 3rd-party [pre-generation of plugins.vim](http://genkisugimoto.com/blog/manage-vim-plugins-via-yaml/) but native solution would be much better.

**Comment by Shougo** [comment]
Because, I don't like YAML format.
Please see the link.

http://npf.io/2014/08/intro-to-toml/

> Now I, of course, can use something like 3rd-party pre-generation of plugins.vim but native solution would be much better.

Sorry, I have not found native slution without if_ruby....
I need correct YAML parser in VimL.
You cannot execute if_ruby code in neovim.

**Comment by amerlyq** [comment]
How about this native [yaml loader in VimL](http://www.vim.org/scripts/script.php?script_id=3190).
Through all Yaml [implementations](http://yaml.org/) there is also PyYaml for python, which would be more robust, if using native VimL isn't mandatory. Then you could use something like this:
```VimL
function! LoadFromYAML(path)
if has('python3')| let pyt='python3' | elseif has('python2') | let pyt='python2' | finish |endif
" ALT: py3file load_yaml.py
exe pyt . ' << endofpython'
	import vim, yaml;
	with open(vim.eval("a:path")) as f:
		plugins = yaml.safe_load(f)
	for src, opts in plugins.items():
		vim.command("NeoBundle '{!s:s}', {}".format(src, opts))
endofpython
endfunc
```
And then file format would be:
```Yaml
Shougo/deoplete.nvim:
  depends: 'Shougo/context_filetype.vim'
  insert: 1
  neovim: 1

Shougo/neosnippet.vim:
  depends: 
    - Shougo/neosnippet-snippets
    - Shougo/context_filetype.vim
  insert: 1
  filetypes: snippet
  unite_sources: [neosnippet, neosnippet/user, neosnippet/runtime]
...

```
