### ISSUE TITLE
Support for string value in 'disabled' -- eval and use result.

### ISSUE THREAD

**Issue by amerlyq** [Shougo/neobundle.vim#476]
I try to befriend nvim+TRUE_COLOR in my yaml loader, mentioned in #450.
I think the same problem will arise in TOML configs also.
Suppose we need complex 'disable' field in our textual ```plugins.*``` with ```ft!=vimscript```.
```Yaml
frankier/neovim-colors-solarized-truecolor-only:
  disable: '!exists("$NVIM_TUI_ENABLE_TRUE_COLOR")'
  lazy: 0

altercation/vim-colors-solarized:
  disable: 'exists("$NVIM_TUI_ENABLE_TRUE_COLOR")'
  lazy: 0
```
Problem is that string values converted to ```0``` in conditions,  so both plugins loaded always.
Actually, could you add additional checking for 'disable' field -- if it has string value -- then eval it and use return value?
